---
name: Install secrets prior to deploying applications
hosts: masters
become: true
vars_files:
  - vars/github.yml
  - vars/k8s.yml
  - vars/gitops.yml
  - vars/k8s-goflights-secrets.yml
roles:
  - secrets