# site.yml
- name: Run Ansible Playbooks in Order with Delay
  hosts: localhost
  gather_facts: false

  vars:
    pause_between: 60

  tasks:
    - name: Install Kubernetes
      include: playbook-k8s.yml

    - name: Pause between steps
      pause:
        seconds: "{{ pause_between }}"

    - name: Configure K8s Aliases and Install Helm
      include: playbook-k8s-extras.yml

    - name: Pause between steps
      pause:
        seconds: "{{ pause_between }}"

    - name: Configure MetalLB Networking and Install Traefik
      include: playbook-k8s-networking.yml

    - name: Pause between steps
      pause:
        seconds: "{{ pause_between }}"

    - name: Install ArgoCD
      include: playbook-argocd.yml

    - name: Pause between steps
      pause:
        seconds: "{{ pause_between }}"

    - name: Install Cert-Manager
      include: playbook-cert-manager.yml

    - name: Pause between steps
      pause:
        seconds: "{{ pause_between }}"

    - name: Deploy CI/CD App with ArgoCD
      include: playbook-install-ci-cd-app.yml
