---
- name: Install required packages for Kubernetes
  ansible.builtin.package:
    name: 
      - ca-certificates
      - curl
      - gnupg
    state: present
    update_cache: yes
  become: true

- name: Add Kubernetes GPG key
  ansible.builtin.apt_key:
    url: https://pkgs.k8s.io/core:/stable:/v1.33/deb/Release.key
    dest: /etc/apt/keyrings/kubernetes-apt-keyring.gpg
    mode: '0644'
    state: present
  become: true

- name: Add Kubernetes repository
  ansible.builtin.apt_repository:
    repo: "deb [arch=amd64 signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.33/deb/ /"
    state: present
  become: true


- name: Update APT cache
  ansible.builtin.apt:
    update_cache: yes
  become: true

- name: Install Kubernetes components
  ansible.builtin.package:
    name:
      - kubelet
      - kubeadm
      - kubectl
    state: present
    update_cache: yes
  become: true

  - name: Mark Kubernetes packages to hold
  ansible.builtin.apt_mark:
    name:
      - kubelet
      - kubeadm
      - kubectl
    state: hold
  become: true  

- name: Enable and start kubelet service
  ansible.builtin.systemd:
    name: kubelet
    state: started
    enabled: true
  register: kubelet_status
  become: true