---
# https://docs.ansible.com/ansible/latest/collections/kubernetes/core/k8s_module.html

- name: Create ArgoCD HTTPS secret for pulling manifests
  kubernetes.core.k8s:
    state: present
    kubeconfig: "{{ kubeconfig_path }}"

    definition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: github-https-creds
        namespace: argocd
        annotations:
          argocd.argoproj.io/secret-type: repository
      type: Opaque
      stringData:
        url: "{{ github_gitops_repo_url }}"
        username: "git"
        password: "{{ github_pat }}"

- name: Create ArgoCD SSH secret for ArgoCD Image Updater push
  kubernetes.core.k8s:
    state: present
    kubeconfig: "{{ kubeconfig_path }}"
    definition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: github-ssh-creds
        namespace: argocd
        annotations:
          argocd.argoproj.io/secret-type: repository
      type: Opaque
      stringData:
        url: "{{ github_gitops_repo_ssh_url }}"
        sshPrivateKey: "{{ github_ssh_private_key }}"




# - name: Copy ArgoCD Application manifest
#   ansible.builtin.copy:
#     src: ci-cd-app.yaml
#     dest: /tmp/ci-cd-app.yaml
#     owner: ubuntu
#     group: ubuntu
#     mode: "0644"

- name: Clone gitops-apps repository
  ansible.builtin.git:
    repo: "{{ gitops_apps_repo_url }}"
    dest: "{{ gitops_apps_dest }}"
    version: "{{ gitops_apps_branch }}"
    force: yes

- name: Create ArgoCD Application
  kubernetes.core.k8s:
    state: present
    src:"{{ gitops_apps_dest }}/{{ ci-cd-app_app_manifest }}"
    kubeconfig: "{{ kubeconfig_path }}"
