---
- name: Install pre-requisites for containerd
  ansible.builtin.package:
    name: 
    - ca-certificates
    - curl
    - gnupg
    state: present
    update_cache: yes

# Specific to Ubuntu
# https://docs.ansible.com/ansible/latest/collections/ansible/builtin/get_url_module.html#ansible-collections-ansible-builtin-get-url-module
- name: Ensure /etc/apt/keyrings directory exists
  ansible.builtin.file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'

# Specific to Ubuntu
# https://docs.ansible.com/ansible/latest/collections/ansible/builtin/get_url_module.html#ansible-collections-ansible-builtin-get-url-module
- name: Add Docker GPG key
  ansible.builtin.get_url:
    url: "https://download.docker.com/linux/ubuntu/gpg"
    dest: /etc/apt/keyrings/docker.asc
    mode: '0644'

# Specific to Ubuntu
# https://docs.ansible.com/ansible/latest/collections/ansible/builtin/apt_repository_module.html#ansible-collections-ansible-builtin-apt-repository-module
- name: Add containerd repository
  ansible.builtin.apt_repository:
    repo: "deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
    state: present



- name: Install containerd
  ansible.builtin.package:
    name: containerd.io
    state: present
    update_cache: yes

# https://docs.ansible.com/ansible/latest/collections/ansible/builtin/copy_module.html#ansible-collections-ansible-builtin-copy-module
- name: Create containerd configuration file
  ansible.builtin.copy:
    src: files/containerd_config.toml
    dest: /etc/containerd/config.toml
    owner: root
    group: root
    mode: '0644'
    backup: yes    

# https://docs.ansible.com/ansible/latest/collections/ansible/builtin/systemd_service_module.html#ansible-collections-ansible-builtin-systemd-service-module
# Restarting the containerd service to apply the new configuration
- name: Restart and enable(start when booted) containerd service
  ansible.builtin.systemd:
    name: containerd
    state: restarted
    enabled: true
    daemon_reload: true
  register: containerd_status

# https://docs.ansible.com/ansible/latest/collections/ansible/builtin/command_module.html#ansible-collections-ansible-builtin-command-module
- name: Wait for containerd to become active
  ansible.builtin.command: systemctl is-active containerd
  register: containerd_check
  retries: 5
  delay: 2
  until: containerd_check.stdout == "active"

# https://docs.ansible.com/ansible/latest/collections/ansible/builtin/assert_module.html#ansible-collections-ansible-builtin-assert-module
- name: Assert containerd is active and running
  ansible.builtin.assert:
    that:
      - containerd_check.stdout == "active"
    fail_msg: "Containerd is not running!"
    success_msg: "Containerd is active and running."