---
- name: Install prerequisites for containerd
  ansible.builtin.package:
    name: 
    - ca-certificates
    - curl
    - gnupg
    state: present
    update_cache: yes
  become: true

# https://docs.ansible.com/ansible/latest/collections/ansible/builtin/apt_key_module.html#ansible-collections-ansible-builtin-apt-key-module
- name: Add containerd GPG key
  ansible.builtin.apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    dest: /etc/apt/keyrings/docker.asc
    mode: '0644'
    state: present
  become: true

# https://docs.ansible.com/ansible/latest/collections/ansible/builtin/apt_repository_module.html#ansible-collections-ansible-builtin-apt-repository-module
- name: Add containerd repository
  ansible.builtin.apt_repository:
    repo: deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable
    state: present
  become: true

- name: Install containerd
  ansible.builtin.package:
    name: containerd.io
    state: present
    update_cache: yes
  become: true